version: '3.1'

services:
  db_users:
    image: mysql:latest
    container_name: mysql_users_container
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: users
    ports:
      - "3307:3306"
    volumes:
      - db_users_data:/var/lib/mysql

  db_profiles_talent:
    image: mysql:latest
    container_name: mysql_profiles_talent_container
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: profiles_talent
    ports:
      - "3308:3306"
    volumes:
      - db_profiles_talent_data:/var/lib/mysql

  db_auth:
    image: mysql:latest
    container_name: mysql_auth_container
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: auth
    ports:
      - "3309:3306"
    volumes:
      - db_auth_data:/var/lib/mysql
      
volumes:
  db_users_data:
  db_profiles_talent_data: