server:
  port: 8762

spring:
  application:
    name: ms-auth-gateway
  main:
    allow-bean-definition-overriding: true
  cloud:
    routes:
      - id: ms-users
        uri: lb://ms-users-route
        predicates:
          Path=/v1/users/**
      - id: ms-profiles
        uri: lb://ms-profiles-route
        predicates:
          Path=/v1/profiles/**
  security:
    oauth2:
      client:
        registration:
          gateway:
            provider: spring
            client-id: client
            client-secret: secret
            scope: openid, profile
            authorization-grant-type: authorization_code
            redirect-uri: http://127.0.0.1:8090/login/oauth2/code/gateway
        provider:
          spring:
            issuer-uri: http://localhost:9000