server:
  port: 8764
spring:
  application:
    name: ms-profiles
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:mysql://localhost:3307/profiles_talent
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database: mysql
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
